### ISSUE TITLE
REPL Lag issues while using JuliaCon and OhMyREPL

### ISSUE THREAD

**Issue by roflmaostc** [JuliaCon/JuliaCon.jl#37] opened 2024-07-10 12:46 UTC
Hi,

using JuliaCon and OhMyREPL together somehow triggers some lag.
Without OhMyREPL this does not happen. Julia 1.11 seems to be a bit faster.

https://github.com/JuliaCon/JuliaCon.jl/assets/19436526/0ae20b67-af89-46ad-b9c6-831492f55fa6

CCing @KristofferC because not sure which package causes it

Best,

Felix

**Comment by carstenbauer** [comment] 2024-07-11 07:09
Interesting... I see this also with a 2023 version of this package on 1.10.4. Might make sense to check other Julia versions as well.

AFAICS, this isn't a JuliaCon.jl issue but a OhMyThreads.jl issue. Why? Because we don't do anything fancy here in this package and nothing related to typing/tab completion and else.

**Comment by roflmaostc** [comment] 2024-07-11 08:06
OhMyREPL.jl yeah.

But OhMyREPL on its own does not have this issue, so it seems to be some of the dependencies or this package itself which causes this lag (probably some recompilation of OhMyREPL?)

**Comment by roflmaostc** [comment] 2024-07-11 08:13
It seems to be some of the dependencies.

Try loading TimesZones or DataFrames. The other package do not cause this lag

```julia
julia> using TimeZones

julia> dasdasdasdsadsadasdsadasdasdasdadscd
```

**Comment by carstenbauer** [comment] 2024-07-12 06:40
I can confirm that the lag happens for TimeZones.jl and DataFrames.jl (re-confirming that this isn't a JuliaCon.jl issue). Looking at the shared dependencies between those two packages, InlineStrings.jl could be the culprit. Hence, the interaction between InlineStrings.jl and OhMyREPL.jl should be investigated. I'll close this issue and open one over at OhMyREPL.jl.

**Closed as completed by carstenbauer** 2024-07-12 06:40 UTC
Labels: upstream
